Examen/Controllers/AlumnoGradoController.cs
using Examen.Database.Tables;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PluginSQL;

namespace Examen.Controllers
{
    public class AlumnoGradoController : Controller
    {
        // GET: AlumnoGradoController
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.Redirect("/account");
            }
            return View();
        }

        // GET: AlumnoGradoController/Details/5
        public ActionResult Details(int id)
        {
            AlumnoGrado model = AlumnoGrado.Find(id);
            return View(model);
        }

        // GET: AlumnoGradoController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AlumnoGradoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AlumnoGrado model)
        {
            try
            {
                if (model.Insert())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch (Exception ex)
            {
                LOG.WriteLine($"[AlumnoGrado Create] {ex}");
                return View();
            }
        }

        // GET: AlumnoGradoController/Edit/5
        public ActionResult Edit(int id)
        {
            AlumnoGrado model = AlumnoGrado.Find(id);
            return View(model);
        }

        // POST: AlumnoGradoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AlumnoGrado model)
        {
            try
            {
                if (model.Update())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch (Exception ex)
            {
                LOG.WriteLine($"[EDIT] {ex}");
                return View();
            }
        }

        // GET: AlumnoGradoController/Delete/5
        public ActionResult Delete(int id)
        {
            AlumnoGrado model = AlumnoGrado.Find(id);
            return View(model);
        }

        // POST: AlumnoGradoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, AlumnoGrado model)
        {
            try
            {
                if (model.Delete())
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Controllers/AlumnosController.cs
using Examen.Database.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PluginSQL;

namespace Examen.Controllers
{
    public class AlumnosController : Controller
    {
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.Redirect("/account");
            }
            return View();
        }

        // GET: AlumnosController/Details/5
        public ActionResult Details(int id)
        {
            Alumno model = Alumno.Find(id);
            return View(model);
        }

        // GET: AlumnosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AlumnosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Alumno model)
        {
            try
            {
                if (model.Insert())
                {
                    return RedirectToAction(nameof(Index));
                }
             
                return View();
            }
            catch(Exception ex)
            {
                LOG.WriteLine($"[Alumno Create] {ex}");
                return View();
            }
        }

        // GET: AlumnosController/Edit/5
        public ActionResult Edit(int id)
        {
            Alumno model = Alumno.Find(id);
            return View(model);
        }

        // POST: AlumnosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Alumno model)
        {
            try
            {
                if (model.Update())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch(Exception ex)
            {
                LOG.WriteLine($"[EDIT] {ex}");
                return View();
            }
        }

        // GET: AlumnosController/Delete/5
        public ActionResult Delete(int id)
        {
            Alumno model = Alumno.Find(id);
            return View(model);
        }

        // POST: AlumnosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Alumno model)
        {
            try
            {
                if (model.Delete())
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Controllers/GradosController.cs
using Examen.Database.Tables;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PluginSQL;

namespace Examen.Controllers
{
    public class GradosController : Controller
    {
        // GET: GradosController
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.Redirect("/account");
            }
            return View();
        }

        // GET: GradosController/Details/5
        public ActionResult Details(int id)
        {
            Grado model = Grado.Find(id);
            return View(model);
        }

        // GET: GradosController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GradosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Grado model)
        {
            try
            {
                if (model.Insert())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch (Exception ex)
            {
                LOG.WriteLine($"[Alumno Create] {ex}");
                return View();
            }
        }

        // GET: GradosController/Edit/5
        public ActionResult Edit(int id)
        {
            Grado model = Grado.Find(id);
            return View(model);
        }

        // POST: GradosController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Grado model)
        {
            try
            {
                if (model.Update())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch (Exception ex)
            {
                LOG.WriteLine($"[EDIT] {ex}");
                return View();
            }
        }

        // GET: GradosController/Delete/5
        public ActionResult Delete(int id)
        {
            Grado model = Grado.Find(id);
            return View(model);
        }

        // POST: GradosController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Grado model)
        {
            try
            {
                if (model.Delete())
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Controllers/ProfesoresController.cs
using Examen.Database.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PluginSQL;

namespace Examen.Controllers
{

    public class ProfesoresController : Controller
    {
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return this.Redirect("/account");
            }
            return View();
        }

        // GET: ProfesoresController/Details/5
        public ActionResult Details(int id)
        {
            Profesor model = Profesor.Find(id);
            return View(model);
        }

        // GET: ProfesoresController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProfesoresController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Profesor model)
        {
            try
            {
                if (model.Insert())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch (Exception ex)
            {
                LOG.WriteLine($"[Profesor Create] {ex}");
                return View();
            }
        }

        // GET: ProfesoresController/Edit/5
        public ActionResult Edit(int id)
        {
            Profesor model = Profesor.Find(id);
            return View(model);
        }

        // POST: ProfesoresController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Profesor model)
        {
            try
            {
                if (model.Update())
                {
                    return RedirectToAction(nameof(Index));
                }

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ProfesoresController/Delete/5
        public ActionResult Delete(int id)
        {
            Profesor model = Profesor.Find(id);
            return View(model);
        }

        // POST: ProfesoresController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Profesor model)
        {
            try
            {
                if (model.Delete())
                {
                    return RedirectToAction(nameof(Index));
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Examen/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Examen</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Examen.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AvalonTM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alumnos" asp-action="Index">Alumnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Profesores" asp-action="Index">Profesores</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Grados" asp-action="Index">Grados</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AlumnoGrado" asp-action="Index">Alumnos Gados</a>
                        </li>
                    </ul>
                </div>

                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                 <div class="top-row px-4">
                    <a class="btn logout" href="/account/logout"> Logout </a>
                  </div>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AvalonTM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>